# Generated by Django 3.0.2 on 2020-07-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200721_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='owner',
        ),
    ]
