# Generated by Django 3.0.2 on 2020-07-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('api', '0003_remove_channel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='channel_followings',
            field=models.ManyToManyField(blank=True, null=True, to='channel.Channel'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_followings',
            field=models.ManyToManyField(blank=True, null=True, related_name='_account_user_followings_+', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Account'),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
